language: python
python:
  - "3.4"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  - export DISPLAY=:99.0
  - sleep 5
install: "pip install -r requirements.txt"
script:
  - python manage.py test rolabola
  - python manage.py test functional_tests.tests.MessageTest
notifications:
  slack: rolabola:gp20B9T95TF94Y7azgyG74xp
