language: python
python:
  - "3.4"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.17.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - export DISPLAY=:99.0
  - sleep 3
install: "pip install -r requirements.txt"
script:
  - python manage.py test
notifications:
  slack: rolabola:gp20B9T95TF94Y7azgyG74xp
