language: python
python:
  - "3.4"
before_script:
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
install: "pip install -r requirements.txt"
script:
  - python manage.py test rolabola
  - python manage.py test functional_tests.tests.MessageTest
notifications:
  slack: rolabola:gp20B9T95TF94Y7azgyG74xp
addons:
  sauce_connect:
    username: "asiviero"
    access_key: "46c0c316-8475-4326-8821-42b424756f5f"
