language: python
python:
  - "3.4"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install: "pip install -r requirements.txt"
script:
  - python test rolabola
  - python test functional_tests
