language: python
python:
  - "3.4"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: "pip install -r requirements.txt"
script:
  - python manage.py test rolabola
  - python manage.py test functional_tests.tests.NewVisitorTest
  - python manage.py test functional_tests.tests.SearchTest
  - python manage.py test functional_tests.tests.GroupTest
  - python manage.py test functional_tests.tests.MatchTest
  - python manage.py test functional_tests.tests.CalendarTest
  - python manage.py test functional_tests.tests.MatchConfirmationTest
  - python manage.py test functional_tests.tests.VenueTest
